#!/bin/sh
if [ $# -ne 1 ]; then
echo "necesitas un parametro [start|stop]"
     exit 22
fi
case $1  in
"start")


##Variables para no tener que poner siempre la ip
DMZ_IP_SAD=172.20.120.254
LAN_IP_SAD=192.168.120.254
WAN_IP_SAD=10.3.4.164
DMZ_IP=172.20.120.0/24
LAN_IP=192.168.120.0/24
DMZ_IP_SRI=172.20.120.22
DMZ_IF=ens3
WAN_IF=ens4
LAN_IF=ens8
##Politicas por defecto
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
iptables -P INPUT DROP

##Borrar reglas al ejecutar script
iptables -F
iptables -t nat -F
##Reglas para permitir SSH 1,2,3-
####WAN
iptables -A INPUT -i $WAN_IF -d $WAN_IP_SAD -p tcp --dport 2222  -j ACCEPT
iptables -A OUTPUT -o $WAN_IF -s $WAN_IP_SAD -p tcp --sport 2222  -j ACCEPT
####LAN
iptables -A INPUT -i $LAN_IF -d $LAN_IP_SAD -p tcp --dport 2222  -j ACCEPT
iptables -A OUTPUT -o $LAN_IF -s $LAN_IP_SAD -p tcp --sport 2222  -j ACCEPT
####DMZ
iptables -A INPUT -i $DMZ_IF -d $DMZ_IP_SAD -p tcp --dport 2222  -j ACCEPT
iptables -A OUTPUT -o $DMZ_IF -s $DMZ_IP_SAD -p tcp --sport 2222  -j ACCEPT

##Reglas para permitir DHCP
####LAN
iptables -A INPUT -i $LAN_IF -p udp --sport 68 --dport 67 -j ACCEPT
iptables -A OUTPUT -o $LAN_IF -p udp --dport 68 --sport 67 -j ACCEPT
####DMZ
iptables -A INPUT -i $DMZ_IF -p udp --sport 68 --dport 67 -j ACCEPT
iptables -A OUTPUT -o $DMZ_IF -p udp --dport 68 --sport 67 -j ACCEPT

#Acceso HTTP->DMZ 4-
iptables -t nat -A PREROUTING -i $LAN_IF -p tcp --dport 80 -j DNAT --to  $DMZ_IP_SAD
iptables -A FORWARD -i $LAN_IF -s $LAN_IP -p tcp --dport 80 -d $DMZ_IP -o $DMZ_IF -j ACCEPT
iptables -A FORWARD -o $LAN_IF -d $LAN_IP -p tcp --dport 80 -s $DMZ_IP -i $DMZ_IF -j ACCEPT


#Acceso HTTPS-> DMZ 5-
iptables -t nat -A PREROUTING -i $LAN_IF -p tcp --dport 443 -j DNAT --to  $DMZ_IP_SAD
iptables -A FORWARD -i $LAN_IF -s $LAN_IP -p tcp --dport 443 -d $DMZ_IP -o $DMZ_IF -j ACCEPT
iptables -A FORWARD -o $LAN_IF -d $LAN_IP -p tcp --sport 443 -s $DMZ_IP -i $DMZ_IF -j ACCEPT

#6- SSH -> SRI
iptables -t nat -A PREROUTING -i $WAN_IF -d $WAN_IP_SAD -p tcp --dport 22 -j DNAT --to $DMZ_IP_SAD
iptables -A FORWARD -i $WAN_IF -o $DMZ_IF -p tcp --dport 22 -d $DMZ_IP_SRI -j ACCEPT
iptables -A FORWARD -o $WAN_IF -i $DMZ_IF -p tcp --sport 22 -s $DMZ_IP_SRI -j ACCEPT

#7-Repositorios desde servidores
iptables -A FORWARD -i $DMZ_IF -d $WAN_IP_SAD -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -o $DMZ_IF -s $WAN_IP_SAD -p tcp --sport 80 -j ACCEPT
iptables -t nat -A PREROUTING -s $DMZ_IP -i $WAN_IF -p tcp  --dport 80 -j DNAT --to $WAN_IP_SAD

#9- DNS LAN -> DMZ
iptables -A FORWARD -i $LAN_IF -s $LAN_IP -o $DMZ_IF -d $DMZ_IP -p udp --dport 53 -j ACCEPT
iptables -A FORWARD -o $LAN_IF -s $LAN_IP -i $DMZ_IF -d $DMZ_IP -p udp --sport 53 -j ACCEPT


#10- HTTP LAN -> DMZ
iptables -A FORWARD -i $DMZ_IF -s $DMZ_IP -o $LAN_IF -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -o $DMZ_IF -d $DMZ_IP -i $LAN_IF -p tcp --sport 80 -j ACCEPT


#11- HTTPS LAN -> DMZ
iptables -A FORWARD -i $LAN_IF -s $LAN_IP -p tcp --dport 443 -d $DMZ_IP -o $DMZ_IF -j ACCEPT
iptables -A FORWARD -o $LAN_IF -d $LAN_IP -p tcp --sport 443 -s $DMZ_IP -i $DMZ_IF -j ACCEPT


#PING-12
iptables -A FORWARD -p icmp -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT


#13- HTTTP-> WAN
iptables -A FORWARD -i $LAN_IF -s $LAN_IP -p tcp --dport 80 -j ACCEPT

#14- HTTPS -> WAN
iptables -A FORWARD -i $LAN_IF -s $LAN_IP -p tcp --dport 443 -j ACCEPT

#FIREWALL-DNS
iptables -A OUTPUT -o $DMZ_IF -s $DMZ_IP_SAD -p udp --dport 53 -d $DMZ_IP_SAD -j ACCEPT
iptables -A INPUT -i $DMZ_IF -d $DMZ_IP_SAD -p udp --sport 53 -s $DMZ_IP_SAD -j ACCEPT

iptables -A OUTPUT -o $LAN_IF -s $WAN_IP_SAD -p udp --dport 53 -j ACCEPT
iptables -A INPUT -i $LAN_IF -d $WAN_IP_SAD -p udp --sport 53 -j ACCEPT


;;
"stop")

iptables -P input accept
iptables -P output accept
iptables -P forward accept
;;
*) echo "se necesita un parametro válido [start|stop]"
   exit 23
;;
esac 
exit 0




